#!/usr/bin/env bash

DESCRIPTION="\
Description: Install a release build for the last known good version
"

DEPENDENCIES="\
Dependencies: same as install
"

USAGE="\
Usage: ./release
"

TMP=`mktemp`
wget http://lunarglass.googlecode.com/svn/trunk/LastKnownGood -O $TMP || exit 1
./install --version=`cat $TMP` all || exit 1
mv $TMP ./LastKnownGood
