#!/usr/bin/env bash
DESCRIPTION="\
Description: Run the test suite, record output
"

USAGE="\
Usage: ./run [options]

       Options:
         -h --help        Print out this Usage info
         -l --linux       Run for linux
         -w --windows     (default) Run for windows
"

# Add more tests here as they are created
TESTS=(checkpoint1.frag test.frag flowControl.frag Operations.frag)

function runTests {
    for t in ${TESTS[@]}; do
        echo "  Running $t"

        # Run for TGSI
        $RUNCMD ${OPTIONS[@]} $TGSIOP $t > $t.stdout 2> $t.errout || tail -n 1 $t.errout
        cat $t.errout $t.stdout > tgsi/$t.out

        # Run for GLSL
        $RUNCMD ${OPTIONS[@]} $GLSLOP $t > $t.stdout 2> $t.errout || tail -n 1 $t.errout
        cat $t.errout $t.stdout > glsl/$t.out
        rm $t.stdout $t.errout
    done
}

function showHelp {
    echo "$DESCRIPTION"
    echo "$USAGE"
}

# Default is for windows
RUNCMD=../../glsl/Debug/StandAlone.exe
OPTIONS=(-d)
TGSIOP="--tgsi"
GLSLOP="--glsl"
# Command-line argument Handling

# No arguments passed
if [[ -z "$*" ]]; then runTests; fi;

# Arguments passed
for i in $*; do
    case $i in
        -l|--linux)
            RUNCMD=../../glsl/StandAlone
            runTests
            ;;
        -h|--h)
            showHelp
            exit 0
            ;;
        *)
            showHelp
            exit 1
            ;;
    esac
done

